# Site settings
author: Lydell Gaines
title: Why did I decide to learn Software Engineering
header-img: img/home-bg.png
email: dasnic70@gmail.com
copyright_name: Lydell Gaines
description: > # this means to ignore newlines until "baseurl:"
  Software Emgineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dasnic

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
